### ISSUE TITLE
Report Repacked Files For Unclosed Runs

### ISSUE THREAD

**Issue by blallen** [dmwm/T0#4293]
The current system only sends Repack signals to Storage Manager team if a run is closed. This appears to be intentional, as it is explicitly included in the query used to check if files have been repacked [1]. 

Storage Manager relies on these signals to know if they can safely delete files so waiting until a run is closed can prevent them from deleting any files from a run due to an issue with only a few of them. Depending on the size of the run, this can clog up the streamer space at P5 and lead to unnecessary interventions to prevent them from running of space. 

Additionally, the Storage Manager monitoring shows the number of Repack files, so in the current setup, an open run appears to have nothing repacked, potentially hiding issues or causing alarm when there is no need.

[1] https://github.com/dmwm/T0/blob/master/src/python/T0/WMBS/Oracle/SMNotification/GetFinishedStreamers.py#L26

**Comment by hufnagel** [comment]
The query as written relies on the fileset to be closed since without that requirement this query would pick up files between injection into the Tier0 and being picked up by the Tier0Feeder and forwarded into the correct fileset for processing.

I can rewrite the query though to do this differently...
